spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unimed?useTimezone=true&serverTimezone=UTC
    username: unimed
    password: 12345678
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
